import { countRows, rows } from '../config/db.js';
import { hydrateChapters } from './chapterDataService.js';

function titleFromJson(v:any,f='Untitled'){if(!v||typeof v!=='object')return f;return v.en||v.de||v.te||v.ta||v.kn||Object.values(v).find(Boolean)||f;}
const ctx=` JOIN chapters c ON c.id=x.chapter_id JOIN course_levels l ON l.id=c.level_id JOIN courses co ON co.id=l.course_id `;
function chapterObj(x:any){return{id:x.chapter_id,slug:x.chapter_slug,number:x.chapter_number,title:titleFromJson(x.chapter_title_json,x.chapter_slug),level:x.level_slug??null,course:x.course_slug??null};}

export async function getAdminOverview(){
 const names=['languages','courses','course_levels','chapters','course_categories','course_series','chapter_notes','chapter_transcripts','chapter_vocabulary','chapter_videos','chapter_quiz_questions','chapter_assets','lid_catalogs','lid_cards','content_releases'];
 const vals=await Promise.all(names.map(countRows));const [languages,courses,levels,chapters,categories,series,notes,transcripts,vocabulary,videos,quiz,chapterAssets,lidCatalogs,lidCards,releases]=vals;
 const recent=await rows<any>('SELECT c.id,c.slug,c.number,c.title_json,c.is_active,c.updated_at,l.slug AS level_slug,co.slug AS course_slug FROM chapters c JOIN course_levels l ON l.id=c.level_id JOIN courses co ON co.id=l.course_id ORDER BY c.updated_at DESC LIMIT 6');
 const latestReleases=await rows<any>('SELECT id,module,version,language_code,manifest_public_url,published_at,is_active FROM content_releases ORDER BY published_at DESC LIMIT 6');
 return{counts:{languages,courses,levels,chapters,categories,series,notes,transcripts,vocabulary,videos,quiz,chapterAssets,lidCatalogs,lidCards,releases},health:{courseContentReady:chapters>0,vocabularyReady:vocabulary>0,mediaReady:videos>0||chapterAssets>0,lidReady:lidCatalogs>0&&lidCards>0,publishedContentReady:releases>0},recentChapters:recent.map(c=>({id:c.id,slug:c.slug,number:c.number,title:titleFromJson(c.title_json,c.slug),level:c.level_slug,course:c.course_slug,isActive:Boolean(c.is_active),updatedAt:c.updated_at})),latestReleases};
}
export async function listAdminChapters(q:{level?:string;search?:string;active?:string}){let w='1=1';const p:any[]=[];if(q.level){w+=' AND l.slug=?';p.push(q.level)}if(q.active==='true')w+=' AND c.is_active=1';if(q.active==='false')w+=' AND c.is_active=0';const data=await hydrateChapters(w,p);let out=data.map((c:any)=>({id:c.id,legacyId:c.legacy_id,slug:c.slug,number:c.number,title:titleFromJson(c.title_json,c.slug),titleJson:c.title_json??{},descriptionJson:c.description_json??{},durationSeconds:c.duration_seconds??0,isPremium:Boolean(c.is_premium),isFeatured:Boolean(c.is_featured),isActive:Boolean(c.is_active),updatedAt:c.updated_at,course:c.level?.course?.slug??null,level:c.level?.slug??null,category:c.category,series:c.series,translations:c.chapter_translations??[],counts:{translations:(c.chapter_translations??[]).length,notes:(c.chapter_notes??[]).length,vocabulary:(c.chapter_vocabulary??[]).length,videos:(c.chapter_videos??[]).length,quiz:(c.chapter_quiz_questions??[]).length}}));const s=q.search?.trim().toLowerCase();return s?out.filter(x=>JSON.stringify(x).toLowerCase().includes(s)):out;}
export async function listAdminVocabulary(q:{search?:string;chapterId?:string;limit?:string}){let w='1=1';const p:any[]=[];if(q.chapterId){w+=' AND x.chapter_id=?';p.push(q.chapterId)}if(q.search){w+=' AND (x.german LIKE ? OR x.english LIKE ?)';p.push(`%${q.search}%`,`%${q.search}%`)}p.push(Math.min(Number(q.limit??500),1000));const d=await rows<any>(`SELECT x.*,c.slug AS chapter_slug,c.number AS chapter_number,c.title_json AS chapter_title_json,l.slug AS level_slug,co.slug AS course_slug FROM chapter_vocabulary x ${ctx} WHERE ${w} ORDER BY x.sort_order LIMIT ?`,p);return d.map(x=>({id:x.id,legacyId:x.legacy_id,german:x.german,english:x.english,meaning:x.meaning_json??{},sortOrder:x.sort_order,chapter:chapterObj(x)}));}
export async function listAdminNotes(q:{language?:string;chapterId?:string}){let w='1=1';const p:any[]=[];if(q.language){w+=' AND x.language_code=?';p.push(q.language)}if(q.chapterId){w+=' AND x.chapter_id=?';p.push(q.chapterId)}const d=await rows<any>(`SELECT x.*,c.slug AS chapter_slug,c.number AS chapter_number,c.title_json AS chapter_title_json,l.slug AS level_slug,co.slug AS course_slug FROM chapter_notes x ${ctx} WHERE ${w} ORDER BY x.updated_at DESC`,p);return d.map(x=>({id:x.id,legacyId:x.legacy_id,languageCode:x.language_code,content:x.content,updatedAt:x.updated_at,chapter:chapterObj(x)}));}
export async function listAdminVideos(q:{chapterId?:string}){let w='1=1';const p:any[]=[];if(q.chapterId){w+=' AND x.chapter_id=?';p.push(q.chapterId)}const d=await rows<any>(`SELECT x.*,c.slug AS chapter_slug,c.number AS chapter_number,c.title_json AS chapter_title_json,l.slug AS level_slug,co.slug AS course_slug FROM chapter_videos x ${ctx} WHERE ${w} ORDER BY x.sort_order`,p);return d.map(x=>({...x,chapter:chapterObj(x)}));}
export async function listAdminQuiz(q:{chapterId?:string}){let w='1=1';const p:any[]=[];if(q.chapterId){w+=' AND x.chapter_id=?';p.push(q.chapterId)}const d=await rows<any>(`SELECT x.*,c.slug AS chapter_slug,c.number AS chapter_number,c.title_json AS chapter_title_json,l.slug AS level_slug,co.slug AS course_slug FROM chapter_quiz_questions x ${ctx} WHERE ${w} ORDER BY x.sort_order`,p);return d.map(x=>({...x,chapter:chapterObj(x)}));}
export async function listAdminCategoriesAndSeries(){const categories=await rows<any>('SELECT x.*,c.slug AS course_slug,c.title_json AS course_title_json FROM course_categories x JOIN courses c ON c.id=x.course_id ORDER BY x.sort_order');const series=await rows<any>('SELECT x.*,c.slug AS course_slug,c.title_json AS course_title_json FROM course_series x JOIN courses c ON c.id=x.course_id ORDER BY x.created_at');return{categories:categories.map(x=>({...x,course:{slug:x.course_slug,title_json:x.course_title_json}})),series:series.map(x=>({...x,course:{slug:x.course_slug,title_json:x.course_title_json}}))};}
