import { z } from 'zod';
import { execute, insertRow, row, rows, updateRow, deleteRow } from '../config/db.js';
import { publicUrl } from '../utils/storage.js';

const Uuid=z.string().uuid();const LocalizedJson=z.record(z.string(),z.string().nullable()).default({});const AnyJson=z.record(z.string(),z.any()).default({});
function titleFromJson(v:any,f='Untitled'){if(!v||typeof v!=='object')return f;return v.en||v.de||v.te||v.ta||v.kn||Object.values(v).find(Boolean)||f;}
function snakePatch(input:Record<string,any>,map:Record<string,string>){const o:Record<string,any>={};for(const [a,b] of Object.entries(map))if(Object.prototype.hasOwnProperty.call(input,a))o[b]=input[a];return o;}

export async function listAdminContentOptions(){
 const [languages,courses,levels,chapters,categories,series]=await Promise.all([rows<any>('SELECT code,name,native_name,is_active,sort_order FROM languages ORDER BY sort_order'),rows<any>('SELECT id,slug,title_json,sort_order FROM courses ORDER BY sort_order'),rows<any>('SELECT id,course_id,slug,title_json,sort_order,is_active FROM course_levels ORDER BY sort_order'),rows<any>('SELECT c.id,c.level_id,c.slug,c.number,c.title_json,c.is_active,l.slug AS level_slug,l.course_id,co.slug AS course_slug FROM chapters c JOIN course_levels l ON l.id=c.level_id JOIN courses co ON co.id=l.course_id ORDER BY c.sort_order,c.number'),rows<any>('SELECT id,course_id,name,icon,description,is_active,sort_order FROM course_categories ORDER BY sort_order'),rows<any>('SELECT id,course_id,title,subtitle,description,is_featured,is_active FROM course_series ORDER BY title')]);
 return{languages,courses:courses.map(c=>({...c,levels:levels.filter(l=>l.course_id===c.id)})),categories,series,chapters:chapters.map(c=>({id:c.id,slug:c.slug,number:c.number,title:titleFromJson(c.title_json,c.slug),titleJson:c.title_json??{},isActive:Boolean(c.is_active),levelId:c.level_id,level:c.level_slug,courseId:c.course_id,course:c.course_slug,label:`${c.level_slug??''} · ${String(c.number).padStart(2,'0')} · ${titleFromJson(c.title_json,c.slug)}`}))};
}
export const CoursePatchInput=z.object({slug:z.string().min(1).optional(),title:LocalizedJson.optional(),description:LocalizedJson.optional(),isActive:z.boolean().optional(),sortOrder:z.number().int().optional()});
export const LevelPatchInput=z.object({courseId:Uuid.optional(),slug:z.string().min(1).optional(),title:LocalizedJson.optional(),description:LocalizedJson.optional(),isActive:z.boolean().optional(),sortOrder:z.number().int().optional()});
export const ChapterPatchInput=z.object({levelId:Uuid.optional(),categoryId:Uuid.nullable().optional(),seriesId:Uuid.nullable().optional(),slug:z.string().min(1).optional(),number:z.number().int().positive().optional(),title:LocalizedJson.optional(),description:LocalizedJson.optional(),durationSeconds:z.number().int().nonnegative().optional(),isPremium:z.boolean().optional(),isFeatured:z.boolean().optional(),isActive:z.boolean().optional(),transcriptDe:z.string().nullable().optional(),notesJson:AnyJson.optional(),vocabularyJson:z.any().optional()});
export const CategoryInput=z.object({courseId:Uuid,name:z.string().min(1),icon:z.string().nullable().optional(),description:z.string().nullable().optional(),isActive:z.boolean().default(true),sortOrder:z.number().int().default(0)});export const CategoryPatchInput=CategoryInput.partial();
export const SeriesInput=z.object({courseId:Uuid,title:z.string().min(1),subtitle:z.string().nullable().optional(),description:z.string().nullable().optional(),coverUrl:z.string().nullable().optional(),isFeatured:z.boolean().default(false),isActive:z.boolean().default(true)});export const SeriesPatchInput=SeriesInput.partial();
export const VocabularyInput=z.object({chapterId:Uuid,german:z.string().min(1),english:z.string().nullable().optional(),meaning:AnyJson.optional(),sortOrder:z.number().int().default(0)});export const VocabularyPatchInput=VocabularyInput.partial();
export const NoteInput=z.object({chapterId:Uuid,languageCode:z.string().min(2),content:z.string().min(1)});export const NotePatchInput=NoteInput.partial();
export const VideoInput=z.object({chapterId:Uuid,title:z.string().min(1).default('Video Overview'),videoUrl:z.string().min(1),thumbnailUrl:z.string().nullable().optional(),durationSeconds:z.number().int().nonnegative().default(0),isEnabled:z.boolean().default(true),isPremium:z.boolean().default(false),showAsPreview:z.boolean().default(false),sortOrder:z.number().int().default(0)});export const VideoPatchInput=VideoInput.partial();
export const QuizInput=z.object({chapterId:Uuid,sourceTable:z.string().default('admin'),question:z.string().min(1),options:AnyJson,correctOption:z.string().min(1),explanation:z.string().nullable().optional(),sortOrder:z.number().int().default(0),isActive:z.boolean().default(true)});export const QuizPatchInput=QuizInput.partial();
export const AssetPatchInput=z.object({chapterId:Uuid.optional(),languageCode:z.string().nullable().optional(),assetType:z.string().min(1).optional(),storagePath:z.string().min(1).optional(),durationSeconds:z.number().int().nonnegative().nullable().optional(),sizeBytes:z.number().int().nonnegative().nullable().optional(),sha256:z.string().nullable().optional(),version:z.string().optional(),isActive:z.boolean().optional()});

export async function updateCourse(id:string,input:z.infer<typeof CoursePatchInput>){return updateRow('courses',id,snakePatch(CoursePatchInput.parse(input),{slug:'slug',title:'title_json',description:'description_json',isActive:'is_active',sortOrder:'sort_order'}));}export const deleteCourse=(id:string)=>deleteRow('courses',id);
export async function updateLevel(id:string,input:z.infer<typeof LevelPatchInput>){return updateRow('course_levels',id,snakePatch(LevelPatchInput.parse(input),{courseId:'course_id',slug:'slug',title:'title_json',description:'description_json',isActive:'is_active',sortOrder:'sort_order'}));}export const deleteLevel=(id:string)=>deleteRow('course_levels',id);
export async function updateChapter(id:string,input:z.infer<typeof ChapterPatchInput>){return updateRow('chapters',id,snakePatch(ChapterPatchInput.parse(input),{levelId:'level_id',categoryId:'category_id',seriesId:'series_id',slug:'slug',number:'number',title:'title_json',description:'description_json',durationSeconds:'duration_seconds',isPremium:'is_premium',isFeatured:'is_featured',isActive:'is_active',transcriptDe:'transcript_de',notesJson:'notes_json',vocabularyJson:'vocabulary_json'}));}export const deleteChapter=(id:string)=>deleteRow('chapters',id);
export async function createCategory(input:z.infer<typeof CategoryInput>){const p=CategoryInput.parse(input);return insertRow('course_categories',{course_id:p.courseId,name:p.name,icon:p.icon??null,description:p.description??null,is_active:p.isActive,sort_order:p.sortOrder});}export async function updateCategory(id:string,input:z.infer<typeof CategoryPatchInput>){return updateRow('course_categories',id,snakePatch(CategoryPatchInput.parse(input),{courseId:'course_id',name:'name',icon:'icon',description:'description',isActive:'is_active',sortOrder:'sort_order'}));}export const deleteCategory=(id:string)=>deleteRow('course_categories',id);
export async function createSeries(input:z.infer<typeof SeriesInput>){const p=SeriesInput.parse(input);return insertRow('course_series',{course_id:p.courseId,title:p.title,subtitle:p.subtitle??null,description:p.description??null,cover_url:p.coverUrl??null,is_featured:p.isFeatured,is_active:p.isActive});}export async function updateSeries(id:string,input:z.infer<typeof SeriesPatchInput>){return updateRow('course_series',id,snakePatch(SeriesPatchInput.parse(input),{courseId:'course_id',title:'title',subtitle:'subtitle',description:'description',coverUrl:'cover_url',isFeatured:'is_featured',isActive:'is_active'}));}export const deleteSeries=(id:string)=>deleteRow('course_series',id);
export async function createVocabulary(input:z.infer<typeof VocabularyInput>){const p=VocabularyInput.parse(input);return insertRow('chapter_vocabulary',{chapter_id:p.chapterId,german:p.german,english:p.english??null,meaning_json:p.meaning??{},sort_order:p.sortOrder});}export async function updateVocabulary(id:string,input:z.infer<typeof VocabularyPatchInput>){return updateRow('chapter_vocabulary',id,snakePatch(VocabularyPatchInput.parse(input),{chapterId:'chapter_id',german:'german',english:'english',meaning:'meaning_json',sortOrder:'sort_order'}));}export const deleteVocabulary=(id:string)=>deleteRow('chapter_vocabulary',id);
export async function createNote(input:z.infer<typeof NoteInput>){const p=NoteInput.parse(input);const ex=await row<any>('SELECT id FROM chapter_notes WHERE chapter_id=? AND language_code=?',[p.chapterId,p.languageCode]);return ex?updateRow('chapter_notes',ex.id,{content:p.content}):insertRow('chapter_notes',{chapter_id:p.chapterId,language_code:p.languageCode,content:p.content});}export async function updateNote(id:string,input:z.infer<typeof NotePatchInput>){return updateRow('chapter_notes',id,snakePatch(NotePatchInput.parse(input),{chapterId:'chapter_id',languageCode:'language_code',content:'content'}));}export const deleteNote=(id:string)=>deleteRow('chapter_notes',id);
export async function createVideo(input:z.infer<typeof VideoInput>){const p=VideoInput.parse(input);return insertRow('chapter_videos',{chapter_id:p.chapterId,title:p.title,video_url:p.videoUrl,thumbnail_url:p.thumbnailUrl??null,duration_seconds:p.durationSeconds,is_enabled:p.isEnabled,is_premium:p.isPremium,show_as_preview:p.showAsPreview,sort_order:p.sortOrder});}export async function updateVideo(id:string,input:z.infer<typeof VideoPatchInput>){return updateRow('chapter_videos',id,snakePatch(VideoPatchInput.parse(input),{chapterId:'chapter_id',title:'title',videoUrl:'video_url',thumbnailUrl:'thumbnail_url',durationSeconds:'duration_seconds',isEnabled:'is_enabled',isPremium:'is_premium',showAsPreview:'show_as_preview',sortOrder:'sort_order'}));}export const deleteVideo=(id:string)=>deleteRow('chapter_videos',id);
export async function createQuiz(input:z.infer<typeof QuizInput>){const p=QuizInput.parse(input);return insertRow('chapter_quiz_questions',{chapter_id:p.chapterId,source_table:p.sourceTable,question:p.question,options_json:p.options,correct_option:p.correctOption,explanation:p.explanation??null,sort_order:p.sortOrder,is_active:p.isActive});}export async function updateQuiz(id:string,input:z.infer<typeof QuizPatchInput>){return updateRow('chapter_quiz_questions',id,snakePatch(QuizPatchInput.parse(input),{chapterId:'chapter_id',sourceTable:'source_table',question:'question',options:'options_json',correctOption:'correct_option',explanation:'explanation',sortOrder:'sort_order',isActive:'is_active'}));}export const deleteQuiz=(id:string)=>deleteRow('chapter_quiz_questions',id);
export async function listChapterAssets(q:{chapterId?:string;language?:string;assetType?:string}){const p:any[]=[];let w='1=1';if(q.chapterId){w+=' AND a.chapter_id=?';p.push(q.chapterId)}if(q.language){w+=' AND a.language_code=?';p.push(q.language)}if(q.assetType){w+=' AND a.asset_type=?';p.push(q.assetType)}const data=await rows<any>(`SELECT a.*,c.slug,c.number,c.title_json,l.slug AS level_slug,co.slug AS course_slug FROM chapter_assets a JOIN chapters c ON c.id=a.chapter_id JOIN course_levels l ON l.id=c.level_id JOIN courses co ON co.id=l.course_id WHERE ${w} ORDER BY a.is_active DESC,a.updated_at DESC,a.created_at DESC`,p);return data.map(a=>{const storage=String(a.storage_path??'');let canonical=a.public_url??null;if(storage&&!/^https?:\/\//i.test(storage))canonical=publicUrl(storage);else if(/^https?:\/\/(silver-llama-257051\.hostingersite\.com|deutsch\.berlinpulse\.eu)\/uploads\//i.test(storage)){try{const u=new URL(storage);canonical=`${process.env.PUBLIC_APP_BASE_URL||''}${u.pathname}`}catch{}}else if(/^https?:\/\/[^/]+\.supabase\.co\/storage\/v1\/object\/public\/content\//i.test(storage)){try{const u=new URL(storage);const suffix=u.pathname.split('/storage/v1/object/public/content/')[1]||'';canonical=`${process.env.PUBLIC_APP_BASE_URL||''}/uploads/content/${suffix}`}catch{}}return{...a,public_url:canonical,chapter:{id:a.chapter_id,slug:a.slug,number:a.number,title:titleFromJson(a.title_json,a.slug),level:a.level_slug,course:a.course_slug}}});}
export async function updateChapterAsset(id:string,input:z.infer<typeof AssetPatchInput>){
 const parsed=AssetPatchInput.parse(input);
 const payload=snakePatch(parsed,{chapterId:'chapter_id',languageCode:'language_code',assetType:'asset_type',storagePath:'storage_path',durationSeconds:'duration_seconds',sizeBytes:'size_bytes',sha256:'sha256',version:'version',isActive:'is_active'});
 if(payload.storage_path)payload.public_url=publicUrl(payload.storage_path);
 if(payload.sha256)payload.version=`sha256:${payload.sha256}`;
 const saved:any=await updateRow('chapter_assets',id,payload);
 if(saved?.is_active){
   const lang=saved.language_code??null;
   await execute(
     'UPDATE chapter_assets SET is_active=0 WHERE chapter_id=? AND asset_type=? AND ((language_code=? ) OR (language_code IS NULL AND ? IS NULL)) AND id<>?',
     [saved.chapter_id,saved.asset_type,lang,lang,saved.id]
   );
 }
 return saved;
}
export const deleteChapterAsset=(id:string)=>deleteRow('chapter_assets',id);
